/**
 * FactOrderQueryModel - 自动生成的表格 Schema
 * ⚠️ 此文件由 foggy-gen 自动生成，请勿手动修改
 */
import type { EnhancedColumnSchema, TableSchema } from '@foggy/data-viewer'
import { calculateColumnWidth } from '@foggy/data-viewer'

/** 全量列定义 */
export const allColumns: EnhancedColumnSchema[] = [
  {
    name: 'orderDate$id',
    title: '订单日期(ID)',
    type: 'TEXT',
    filterType: 'dimension',
    filterable: true,
    measure: false,
    aggregatable: false,
    width: calculateColumnWidth('订单日期(ID)', 'TEXT'),
  },
  {
    name: 'orderDate$caption',
    title: '订单日期(名称)',
    type: 'TEXT',
    filterType: 'dimension',
    filterable: true,
    measure: false,
    aggregatable: false,
    memberLookup: {
      enabled: true,
      selectionFieldName: 'orderDate$id',
      displayFieldName: 'orderDate$caption',
      searchable: true,
      pageable: true,
      defaultLimit: 20,
    },
    width: calculateColumnWidth('订单日期(名称)', 'TEXT'),
  },
  {
    name: 'orderDate$year',
    title: '年',
    type: 'TEXT',
    filterType: 'text',
    filterable: true,
    measure: false,
    width: calculateColumnWidth('年', 'TEXT'),
  },
  {
    name: 'orderDate$month',
    title: '月',
    type: 'TEXT',
    filterType: 'text',
    filterable: true,
    measure: false,
    width: calculateColumnWidth('月', 'TEXT'),
  },
  {
    name: 'customer$id',
    title: '客户(ID)',
    type: 'TEXT',
    filterType: 'dimension',
    filterable: true,
    measure: false,
    width: calculateColumnWidth('客户(ID)', 'TEXT'),
  },
  {
    name: 'customer$caption',
    title: '客户(名称)',
    type: 'TEXT',
    filterType: 'dimension',
    filterable: true,
    measure: false,
    memberLookup: {
      enabled: true,
      selectionFieldName: 'customer$id',
      displayFieldName: 'customer$caption',
      searchable: true,
      pageable: true,
      defaultLimit: 20,
    },
    width: calculateColumnWidth('客户(名称)', 'TEXT'),
  },
  {
    name: 'customer$customerType',
    title: '客户类型',
    type: 'TEXT',
    filterType: 'text',
    filterable: true,
    measure: false,
    width: calculateColumnWidth('客户类型', 'TEXT'),
  },
  {
    name: 'customer$province',
    title: '省份',
    type: 'TEXT',
    filterType: 'text',
    filterable: true,
    measure: false,
    width: calculateColumnWidth('省份', 'TEXT'),
  },
  {
    name: 'customer$memberLevel',
    title: '会员等级',
    type: 'TEXT',
    filterType: 'text',
    filterable: true,
    measure: false,
    width: calculateColumnWidth('会员等级', 'TEXT'),
  },
  {
    name: 'store$id',
    title: '门店(ID)',
    type: 'TEXT',
    filterType: 'dimension',
    filterable: true,
    measure: false,
    width: calculateColumnWidth('门店(ID)', 'TEXT'),
  },
  {
    name: 'store$caption',
    title: '门店(名称)',
    type: 'TEXT',
    filterType: 'dimension',
    filterable: true,
    measure: false,
    memberLookup: {
      enabled: true,
      selectionFieldName: 'store$id',
      displayFieldName: 'store$caption',
      searchable: true,
      pageable: true,
      defaultLimit: 20,
    },
    width: calculateColumnWidth('门店(名称)', 'TEXT'),
  },
  {
    name: 'channel$id',
    title: '渠道(ID)',
    type: 'TEXT',
    filterType: 'dimension',
    filterable: true,
    measure: false,
    width: calculateColumnWidth('渠道(ID)', 'TEXT'),
  },
  {
    name: 'channel$caption',
    title: '渠道(名称)',
    type: 'TEXT',
    filterType: 'dimension',
    filterable: true,
    measure: false,
    memberLookup: {
      enabled: true,
      selectionFieldName: 'channel$id',
      displayFieldName: 'channel$caption',
      searchable: true,
      pageable: true,
      defaultLimit: 20,
    },
    width: calculateColumnWidth('渠道(名称)', 'TEXT'),
  },
  {
    name: 'orderId',
    title: '订单ID',
    type: 'STRING',
    filterType: 'text',
    filterable: true,
    measure: false,
    width: calculateColumnWidth('订单ID', 'STRING'),
  },
  {
    name: 'orderStatus',
    title: '订单状态',
    type: 'STRING',
    filterType: 'dict',
    filterable: true,
    measure: false,
    dictId: 'order_status',
    width: calculateColumnWidth('订单状态', 'STRING'),
  },
  {
    name: 'paymentStatus',
    title: '支付状态',
    type: 'STRING',
    filterType: 'dict',
    filterable: true,
    measure: false,
    dictId: 'payment_status',
    width: calculateColumnWidth('支付状态', 'STRING'),
  },
  {
    name: 'orderTime',
    title: '下单时间',
    type: 'DATETIME',
    filterType: 'datetime',
    filterable: true,
    measure: false,
    uiConfig: { format: 'yyyy-MM-dd HH:mm:ss' },
    width: calculateColumnWidth('下单时间', 'DATETIME'),
  },
  {
    name: 'quantity',
    title: '订单总数量',
    type: 'INTEGER',
    filterType: 'number',
    filterable: true,
    measure: true,
    aggregatable: true,
    width: calculateColumnWidth('订单总数量', 'INTEGER'),
  },
  {
    name: 'amount',
    title: '订单总额',
    type: 'MONEY',
    filterType: 'number',
    filterable: true,
    measure: true,
    aggregatable: true,
    width: calculateColumnWidth('订单总额', 'MONEY'),
  },
  {
    name: 'discountAmount',
    title: '折扣金额',
    type: 'MONEY',
    filterType: 'number',
    filterable: true,
    measure: true,
    aggregatable: true,
    width: calculateColumnWidth('折扣金额', 'MONEY'),
  },
  {
    name: 'payAmount',
    title: '订单应付金额',
    type: 'MONEY',
    filterType: 'number',
    filterable: true,
    measure: true,
    aggregatable: true,
    width: calculateColumnWidth('订单应付金额', 'MONEY'),
  },
]

/** 默认可见列 */
export const defaultVisibleColumns = [
  'orderDate$caption',
  'customer$caption',
  'store$caption',
  'channel$caption',
  'orderId',
  'orderStatus',
  'orderTime',
  'quantity',
  'amount',
  'payAmount',
]

/** 默认搜索字段 */
export const defaultSearchFields = ['orderId', 'customer$caption']

/** 表格 Schema */
export const tableSchema: TableSchema = {
  columns: allColumns.filter((c) => defaultVisibleColumns.includes(c.name)),
  searchableFields: defaultSearchFields,
  pageSize: 50,
  showFilters: true,
  showPager: true,
  showSearchToolbar: true,
}
