import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import zhCn from 'element-plus/dist/locale/zh-cn.mjs'
import VxeUI from 'vxe-pc-ui'
import VxeTable from 'vxe-table'
import 'element-plus/dist/index.css'
import 'vxe-pc-ui/lib/style.css'
import 'vxe-table/lib/style.css'
import 'foggy-data-viewer/style.css'
import App from './App.vue'
createApp(App).use(ElementPlus, { locale: zhCn }).use(VxeUI).use(VxeTable).mount('#app')
