
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.foggyframework.fsscript.parser;

/** CUP generated class containing symbol constants. */
public class ExpSymbols {
  /* terminals */
  public static final int QMARK = 64;
  public static final int AT = 76;
  public static final int AS = 68;
  public static final int FROM = 78;
  public static final int DIVISION = 30;
  public static final int QMARK_DOT = 65;
  public static final int GT = 39;
  public static final int REQUEST = 16;
  public static final int CONST = 62;
  public static final int AA = 3;
  public static final int EXPORT = 21;
  public static final int GE = 38;
  public static final int EXP_STRING = 83;
  public static final int LBRACE_DESTR = 49;
  public static final int LIKE = 6;
  public static final int CATCH = 73;
  public static final int COMMA = 33;
  public static final int RBRACE = 50;
  public static final int THROW = 75;
  public static final int RPAREN = 46;
  public static final int LBRACE_OBJ = 48;
  public static final int LT = 41;
  public static final int DOLLAR_LBRACE = 77;
  public static final int LBRACE = 47;
  public static final int LPAREN = 45;
  public static final int FALSE = 14;
  public static final int NOT = 5;
  public static final int LE = 40;
  public static final int MULTI = 29;
  public static final int VAR = 60;
  public static final int EQ = 36;
  public static final int DOLLAR = 80;
  public static final int EQ2 = 37;
  public static final int NUMBER = 84;
  public static final int _EE = 18;
  public static final int TRUE = 13;
  public static final int LONG = 85;
  public static final int PLUS = 28;
  public static final int PERCENT = 32;
  public static final int WHILE = 71;
  public static final int DELETE = 79;
  public static final int SWITCH = 25;
  public static final int FOR = 70;
  public static final int BACKQUOTE = 35;
  public static final int DDDOT = 54;
  public static final int RETURN = 63;
  public static final int CONCAT = 66;
  public static final int TRY = 72;
  public static final int ELSE = 69;
  public static final int BREAK = 58;
  public static final int DOT = 53;
  public static final int DEFAULT_COLON = 23;
  public static final int NULL = 27;
  public static final int EOF = 0;
  public static final int THIS = 15;
  public static final int BANG = 44;
  public static final int DEFAULT = 22;
  public static final int FUNCTION = 59;
  public static final int IMPORT = 19;
  public static final int RSBRACE = 52;
  public static final int MINUS = 31;
  public static final int IN = 7;
  public static final int OR = 10;
  public static final int error = 1;
  public static final int FINALLY = 74;
  public static final int ORR = 11;
  public static final int CONTINUE = 24;
  public static final int IF = 67;
  public static final int INSTANCEOF = 8;
  public static final int ID = 81;
  public static final int NCOUNT = 57;
  public static final int OF = 9;
  public static final int CIMPORT = 20;
  public static final int COLON = 56;
  public static final int LSBRACE = 51;
  public static final int _EVALUATOR = 17;
  public static final int SQM = 34;
  public static final int CASE = 26;
  public static final int NEW = 4;
  public static final int STRING = 82;
  public static final int NO = 55;
  public static final int AND = 2;
  public static final int NF = 43;
  public static final int LET = 61;
  public static final int NE = 42;
  public static final int XOR = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "AA",
  "NEW",
  "NOT",
  "LIKE",
  "IN",
  "INSTANCEOF",
  "OF",
  "OR",
  "ORR",
  "XOR",
  "TRUE",
  "FALSE",
  "THIS",
  "REQUEST",
  "_EVALUATOR",
  "_EE",
  "IMPORT",
  "CIMPORT",
  "EXPORT",
  "DEFAULT",
  "DEFAULT_COLON",
  "CONTINUE",
  "SWITCH",
  "CASE",
  "NULL",
  "PLUS",
  "MULTI",
  "DIVISION",
  "MINUS",
  "PERCENT",
  "COMMA",
  "SQM",
  "BACKQUOTE",
  "EQ",
  "EQ2",
  "GE",
  "GT",
  "LE",
  "LT",
  "NE",
  "NF",
  "BANG",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "LBRACE_OBJ",
  "LBRACE_DESTR",
  "RBRACE",
  "LSBRACE",
  "RSBRACE",
  "DOT",
  "DDDOT",
  "NO",
  "COLON",
  "NCOUNT",
  "BREAK",
  "FUNCTION",
  "VAR",
  "LET",
  "CONST",
  "RETURN",
  "QMARK",
  "QMARK_DOT",
  "CONCAT",
  "IF",
  "AS",
  "ELSE",
  "FOR",
  "WHILE",
  "TRY",
  "CATCH",
  "FINALLY",
  "THROW",
  "AT",
  "DOLLAR_LBRACE",
  "FROM",
  "DELETE",
  "DOLLAR",
  "ID",
  "STRING",
  "EXP_STRING",
  "NUMBER",
  "LONG"
  };
}

